columns: 80
steps:
  - unicode_syntax:
      add_language_pragma: false
  - imports:
      align: group
  - language_pragmas:
      style: compact_line
      remove_redundant: true
  - records: {}
  - tabs:
      spaces: 8
  - trailing_whitespace: {}
language_extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - UnicodeSyntax
